default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/trz_dev.sqlite3

test:
  <<: *default
  database: db/trz_test.sqlite3

production:
  <<: *default
  database: db/trz_prod.sqlite3
